name=AnyHolic
version=1.0.0
author=anyholic@me.com
maintainer=anyholic@me.com
sentence=Tesla CAN Arduino Library
paragraph=Tesla CAN Arduino Library
category=Device Control
url=https://github.com/anyholic/Tesla_CAN
architectures=ESP32-S3
includes=Tesla_CAN.h